production: 
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  database: todoapp
  username: root
  password: web999
  encoding: utf8

development: 
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  database: todoapp
  username: root
  password: web999
  encoding: utf8

test:
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  database: todoapp_test
  username: root
  password: web999
  encoding: utf8

